steps:
  # Entrypoint, timeout and environment variables
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    timeout: 240s
    args: ['beta',
          'run', 
          'deploy', 
          'trigger-svc-kreationsbykgola',
          '--image', 
          '--region',
          'central1',
          'platform',
          'managed',
          '--min-instances',
          '0',
          '--max-instances',
          '1',
           '--allow-unauthenticated']
           