steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 
           'us-central1-docker.pkg.dev/${PROJECT_ID}/modifa_images/myimage', 
           '.']

  # Docker Push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 
           'us-central1-docker.pkg.dev/${PROJECT_ID}/modifa_images/myimage']

  # Entrypoint, timeout and environment variables
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    timeout: 240s
    args: ['beta',
          'run', 
          'deploy', 
          'trigger-svc-kreationsbykgola',
          '--image', 
          'us-central1-docker.pkg.dev/${PROJECT_ID}/modifa_images/kreationsbykgola',
          '--region',
          'central1',
          'platform',
          'managed',
          '--min-instances',
          '0',
          '--max-instances',
          '1',
           '--allow-unauthenticated']
           